### PR TITLE
reverse getrankranking function

### PR DESCRIPTION
**Pull request by juniorbutyeah**

### CODE REVIEW

**Comment by n-tdi** [comment]
https://jdoodle.com/ia/Jke

Testing out the function you provided, does not seem to work as expected.

**Comment by n-tdi** [comment]
The point was that the original function does not work. This requires changes that will make it work.

**Comment by n-tdi** [comment]
The point was that the original function does not work. This requires changes that will make it work. 

The intended use is that anyone with with a ranking, e.g, 1, would have 'aaaa' be returned. Then for 2, 'aaab'. 3 'aaac'. and so on and so forth.

**Review by n-tdi — CHANGES_REQUESTED** [review]
Please read the comment I made explaining as to why this needs changes.

**Comment by juniorbutyeah** [comment]
I don't understand, do you literally want the function to return 'aaaa' if you had rank '1' and so on? Or is that just an example on what you want me to do?

**Comment by n-tdi** [comment]
> I don't understand, do you literally want the function to return 'aaaa' if you had rank '1' and so on? Or is that just an example on what you want me to do?

That was an example, It should be modular.

**Comment by n-tdi** [comment]
wait, @juniorbutyeah i am completely wrong. This will work just fine.

**Pull request merged**
